[project]
name = "mariage"
revision = "1.0"

[profiles.default]

[profiles.production]
SMTP_USER = { required = true }
SMTP_PASSWORD = { required = true }
ADMIN_PASSWORD = { required = true }
SESSION_SECRET = { required = true }
